[install]
# Preferences
auto = "fallback"
peer = true
production = false
frozen-lockfile = false

[install.cache]
# Cache configuration
dir = ".bun-cache"
disable = false

[install.lockfile]
# Lockfile
save = true