import type { APIGatewayEvent, APIGatewayResponse, Handler } from "../../types";
import { getDb } from "../../services/db";
import { success, notFound, badRequest, error, unauthorized } from "../../middlewares/response";
import { getUserIdFromEvent } from "../../utils/auth";

type ReportReason = "spam" | "inappropriate" | "harassment" | "misinformation" | "other";

interface ReportBody {
  reason: ReportReason;
  details?: string;
}

// POST /reviews/comments/:commentId/report - Report a review comment
export const handler: Handler = {
  async handle(event: APIGatewayEvent): Promise<APIGatewayResponse> {
    try {
      const db = await getDb();
      const userId = getUserIdFromEvent(event);
      const commentId = event.pathParameters?.commentId;

      if (!userId) {
        return unauthorized("Authentication required");
      }

      if (!commentId) {
        return badRequest("Comment ID is required");
      }

      let body: ReportBody;
      try {
        body = JSON.parse(event.body || "{}");
      } catch {
        return badRequest("Invalid JSON body");
      }

      const { reason, details } = body;

      const validReasons: ReportReason[] = ["spam", "inappropriate", "harassment", "misinformation", "other"];
      if (!reason || !validReasons.includes(reason)) {
        return badRequest(
          "Valid reason is required: spam, inappropriate, harassment, misinformation, or other"
        );
      }

      // Verify comment exists
      const comment = await db
        .selectFrom("comments")
        .select(["id"])
        .where("id", "=", commentId)
        .executeTakeFirst();

      if (!comment) {
        return notFound("Comment not found");
      }

      // Check if user already reported this comment
      const existingReport = await db
        .selectFrom("reports")
        .select(["id"])
        .where("target_type", "=", "comment")
        .where("target_id", "=", commentId)
        .where("reporter_id", "=", userId)
        .executeTakeFirst();

      if (existingReport) {
        return badRequest("Bạn đã báo cáo bình luận này rồi");
      }

      // Create report (id is auto-generated by database)
      await db
        .insertInto("reports")
        .values({
          reporter_id: userId,
          target_type: "comment",
          target_id: commentId,
          reason,
          details: details ?? null,
          status: "pending",
        })
        .execute();

      return success({
        success: true,
        message: "Báo cáo đã được ghi nhận",
      });
    } catch (err) {
      console.error("[reviews/comment-report] Error:", err);
      return error((err as Error).message);
    }
  },
};
