// Shared TypeScript types for MapVibe
// Database types will be auto-generated by kysely-codegen

// Export database types (will be generated)
// export * from './database';

// ============================================
// API Response Types
// ============================================
export interface ApiResponse<T> {
  data: T;
  error?: string;
  success: boolean;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// ============================================
// Common Types
// ============================================
export type UserRole = "user" | "admin";
export type AccountStatus = "active" | "suspended" | "banned";
export type LocationStatus = "pending" | "approved" | "rejected" | "merged";
export type RestaurantStatus = "approved" | "closed" | "removed";
export type ReviewStatus = "published" | "hidden" | "deleted";
export type PhotoType = "general" | "space" | "food" | "menu" | "video";
export type VoteType = "upvote" | "downvote";

// ============================================
// Rating Types (1-10 scale for approved restaurants)
// ============================================
export interface RestaurantRatings {
  service: number; // 1-10
  location: number; // 1-10
  price: number; // 1-10
  quality: number; // 1-10
  ambiance: number; // 1-10
  overall?: number; // Auto-calculated average
}

export type RatingAspect = keyof Omit<RestaurantRatings, "overall">;

// ============================================
// Location & Address Types
// ============================================
export interface Coordinates {
  lat: number;
  lng: number;
}

export interface Address {
  street: string;
  ward?: string;
  district: string;
  city: string;
  fullAddress?: string;
}
